# Dockerfile

FROM node:16-alpine as build

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn webpack

FROM nginx:1.24.0-alpine-slim
COPY --from=build app/build /usr/share/nginx/html
EXPOSE 80
EXPOSE 8080